let jsurl = [
  // 'static/f2e/gallery/art-template/2.0.3/template.min.js',
  // 'static/f2e/gallery/art-template/3.0/template.js',
  // 'static/f2e/gallery/ckplayer/x/ckplayer.js',
  // 'static/f2e/gallery/form/autocomplete.min.js',
  // 'static/f2e/gallery/html5shiv/3.7.2/html5shiv.min.js',
  // 'static/f2e/gallery/jquery/1.11.1/jquery-1.11.1.min.js',
  // 'static/f2e/gallery/jquery/1.4.2/jquery.min.js',
  // 'static/f2e/gallery/jquery/1.9.1/jquery.js',
  // 'static/f2e/gallery/jquery/1.9.1/jquery.min.js',
  // 'static/global_ued/js/gallery/html5.js',
  // 'static/global_ued/js/gallery/jquery/v1.9.1/jquery.js',
  // 'static/global_ued/js/gallery/jquery/v1.9.1/jquery.min.js',
  // 'static/ketang_9first_com/js/ckplayer/ckplayer.js',
  'static/meadincms/static/jobbon/js/app/index.js',
  'static/meadincms/static/jobbon/js/common.js',
  'static/meadincms/static/jobbon/js/plugins/pagination/pagination.js',
  'static/meadincms/static/jobbon/js/scrollfixed.js',
  'static/sso/js/sso2016.js',
  'static/sso/js/sso_2018.js',
  'static/sso/js/sso.js',
  'static/sso/js/ve_msg_utf8.js',
  // '无   static/ve/suiyi/build/%7Ewebpack.js',
  'static/ve/suiyi/build/feedback.js',
  'static/ve/suiyi/build/search.js',
  'static/ve/suiyi/build/~webpack.js',
  'static/www_veryeast_cn/dist_layer/cock.js',
  'static/www_veryeast_cn/dist_layer/layer.js',
  'static/www_veryeast_cn/feedback/js/feedback.js',
  'static/www_veryeast_cn/feedback/js/ie8click.js',
  'static/www_veryeast_cn/job/js/main.js',
  'static/www_veryeast_cn/job/js/search.js',
  'static/www_veryeast_cn/v2017/js/advertisement_list.js',
  'static/www_veryeast_cn/v2017/js/city_common.js',
  'static/www_veryeast_cn/v2017/js/city_home.js',
  'static/www_veryeast_cn/v2017/js/header_login.js',
  'static/www_veryeast_cn/v2017/js/hotel_list.js',
  // 'static/www_veryeast_cn/v2017/js/jquery-1.9.1.min.js',
  // 'static/www_veryeast_cn/v2017/js/jquery.nivo.slider.pack.js',
  'static/www_veryeast_cn/v2017/js/layer3.js',
  'static/www_veryeast_cn/v2017/js/layer.js',
  'static/www_veryeast_cn/v2017/js/login.js',
  'static/www_veryeast_cn/v2017/js/main_.js',
  'static/www_veryeast_cn/v2017/js/reg_login_popUp.js',
  'static/www_veryeast_cn/v2017/js/sso_ve_login_reg.js',
]

module.exports = jsurl
